In [2]:
import numpy as np

In [ ]:
lista = [1,2,3,4,5,6,7,8,9]

In [ ]:
arr = np.array(lista)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[0]

1

In [ ]:
matriz[2,2]

9

In [ ]:
arr[0:4]

array([1, 2, 3, 4])

In [ ]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [ ]:
cubo = [[ [1,2,3],[3,4,5,6] ] ,[ [7,8,9],[10,11,12] ] ]
cubo = np.array(cubo)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


In [ ]:
cubo

[[[1, 2, 3], [3, 4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

---

In [ ]:
#tipos de datos

In [ ]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [ ]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [ ]:
arr.astype(np.float64)

array([1., 2., 3., 4.])

---

In [ ]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [ ]:
vector = np.array([42,33])
print(vector)
vector.ndim

[42 33]


1

In [ ]:
matriz = np.array( [ [3,4],[1,2] ] )
print(matriz)
matriz.ndim

[[3 4]
 [1 2]]


2

In [ ]:
tensor = np.array( [[ [3,4],[1,2] ],[ [3,4],[1,2] ]] )
print(tensor)
tensor.ndim

[[[3 4]
  [1 2]]

 [[3 4]
  [1 2]]]


3

Agregar o eliminar dimensiones

In [ ]:
vector = np.array([42,33],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[42 33]]]]]]]]]]


10

In [ ]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [ ]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector) #quitar dimensiones
print(vector_2, vector_2.ndim)

[[[[[[[[[[42 33]]]]]]]]]] 10
[42 33] 1


In [ ]:
np.arange(0,101,4) #creacion de un array con un rango definido

array([  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100])

In [ ]:
np.zeros((3,3)) #define un array de 0's

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3)) #define un array de 1's

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.linspace(1,11,10) #crea una distribucion normalizada desde un rango inferior a un rango superior

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

In [ ]:
np.random.rand()

0.14674357160527118

In [ ]:
np.random.rand(4)

array([0.56904274, 0.01631467, 0.39519167, 0.40369321])

In [ ]:
np.random.rand(4,4)

array([[0.82568278, 0.85973324, 0.12115966, 0.74962619],
       [0.6127243 , 0.15743805, 0.067077  , 0.71495961],
       [0.61407166, 0.5158624 , 0.24304779, 0.46688638],
       [0.20934743, 0.72951244, 0.85201157, 0.42359145]])

In [ ]:
np.random.randint(1,15)

12

In [ ]:
np.random.randint(1,100,(10,10)) #-> crea un array de numeros enteros aleatorios, con el segundo parametro se especifican sus dimensiones

array([[55, 82, 41, 33, 53, 22, 71, 28, 35, 88],
       [68, 19, 54, 37,  3, 70, 25, 45, 47, 82],
       [15, 51, 77, 54, 44,  1, 51, 60,  9, 55],
       [64, 50, 93, 81, 77, 15, 86, 60, 92, 26],
       [ 9, 36, 47, 30, 18, 96,  9, 80,  2,  1],
       [23, 77, 19, 25, 60, 39, 61, 77, 59, 36],
       [71, 35,  1, 99, 14,  4, 44, 66, 94, 81],
       [38, 57, 34, 44, 36, 55, 58,  3, 69, 73],
       [50, 88, 12,  6, 26, 13, 43,  3, 38, 62],
       [80, 73, 34, 70, 14, 14, 95, 69, 34, 51]])

---

In [ ]:
#shape y reshape

In [ ]:
arr = np.random.randint(1,10,(3,2)) 

In [ ]:
arr.shape

(3, 2)

In [ ]:
arr.reshape(1,6) #->reordenamiento del array

array([[5, 1, 3, 6, 8, 1]])

In [ ]:
arr.reshape(2,3)

array([[5, 1, 3],
       [6, 8, 1]])

In [ ]:
arr

array([[5, 1],
       [3, 6],
       [8, 1]])

In [ ]:
np.reshape(arr,(2,3),'C') #-> reordenamiento del array

array([[5, 1, 3],
       [6, 8, 1]])

---

In [ ]:
#Funciones principales de numpy

In [ ]:
arr = np.random.randint(1,20,10)

In [ ]:
matriz = arr.reshape(2,5)
matriz

array([[13, 17, 18,  8, 17],
       [ 8, 15, 18, 16, 13]])

In [ ]:
arr.max()

18

In [ ]:
arr.min()

8

In [ ]:
matriz.max(1)

array([18, 18])

In [ ]:
matriz.max(0)

array([13, 17, 18, 16, 17])

In [ ]:
matriz.argmax(0) #-> nos arroja el indice donde esta el valor maximo en el array, por columnas, dado que el parametro es 0

array([0, 0, 0, 1, 0])

In [ ]:
arr.ptp() #-> nos da la diferencia del numero mas alto al mas bajo (max-min)

10

In [ ]:
np.percentile(arr,50) #especifica el percentil que se esta trabajando

15.5

In [ ]:
np.median(arr)

15.5

In [ ]:
np.median(matriz,0) # -> nos arroja la mediana

array([10.5, 16. , 18. , 12. , 15. ])

In [ ]:
np.std(arr) # -> nos arroja la desviación estandar

3.5791060336346563

In [ ]:
np.var(arr) #-> nos arroja la varianza

12.810000000000002

In [ ]:
np.mean(arr) # -> arroja la media (promedio)

14.3

In [ ]:
a = np.array([[1,2],[3,4]])
print(a)
b = np.array([5,6])
print(b)

[[1 2]
 [3 4]]
[5 6]


In [ ]:
b = np.expand_dims(b,axis=0)

In [ ]:
np.concatenate((a,b.T),axis=1) #la T es la transpuesta de una matriz

array([[1, 2, 5],
       [3, 4, 6]])

--- Copy

In [ ]:
array = np.arange(0,11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
trozo_arr = array[0:6]

In [ ]:
trozo_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
trozo_arr[:] = 0
print(trozo_arr)
print(array)

[0 0 0 0 0 0]
[ 0  0  0  0  0  0  6  7  8  9 10]


In [ ]:
array_copy = array.copy()

In [ ]:
array_copy[:] = 0
print(array_copy)
print(array)

[0 0 0 0 0 0 0 0 0 0 0]
[ 0  0  0  0  0  0  6  7  8  9 10]


In [ ]:
#CONDICIONES

In [ ]:
arr = np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
indices_condicion = arr > 5
indices_condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
arr[indices_condicion]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [ ]:
arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

--- operaciones

In [ ]:
lista = [1,2]
lista

[1, 2]

In [ ]:
lista*2 # las listas convencionales de python, no permiten las operaciones en sus elementos

[1, 2, 1, 2]

In [ ]:
new_arr = np.arange(0,10)
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr_2 = new_arr.copy()

In [ ]:
arr_2 * 2 # Los arrays de numpy si permiten operaciones en sus elementos

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
1/arr_2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
new_arr + arr_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
matriz = new_arr.reshape(2,5)
matriz2 = matriz.copy()

In [ ]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
matriz+matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [ ]:
matriz-matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.matmul(matriz,matriz2.T) #Producto punto

array([[ 30,  80],
       [ 80, 255]])

In [3]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96